theme: chrisrhymes/bulma-clean-theme
# Site Settings
title: Harini Palanisamy
tagline: Harini Palanisamy
email: your-email@domain.com
description: >
  Software developent Manager | ML in Investment enthusiast
#baseurl: "/harini-palanisamy"
url: "https://harinipsamy.github.io"
permalink: pretty
author: Harini Palanisamy
avatar: img/blog-pic-b2c.jpg
author_profile: true
#gh_sponsor: harini

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: harinipalanisamy


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true
sitemap: True

sass:
  style: compressed
  source_dir: _sass

google_analytics: UA-166185877-1
# #<!-- Global site tag (gtag.js) - Google Analytics -->
# <script async src="https://www.googletagmanager.com/gtag/js?id=UA-166185877-1"></script>
# <script>
#   window.dataLayer = window.dataLayer || [];
#   function gtag(){dataLayer.push(arguments);}
#   gtag('js', new Date());

#   gtag('config', 'UA-166185877-1');
# </script>


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Harini Palanisamy"
      layout: post
      #image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  products: 
    output: true
    layout: product
    #image: https://via.placeholder.com/800x600
    show_sidebar: false

