remote_theme: bulma-clean-theme

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge

markdown: kramdown
highlighter: rouge

url: "https://harinipsamy.github.io/"
